name: ðŸž Bug Report
description: This form is to report unexpected behavior in our fork of Nx.
labels: ["type: bug"]
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file an issue! ðŸ™ We apologise for any inconvenience this has caused you and are eager to resolve it as soon as possible.

        Help us help you! We value your time and appreciate your efforts in ensuring that we can reproduce the issue. The more details you provide, the easier it will be for us to fix the problem.

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: What behavior are you currently experiencing?
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What behavior do you expect to occur?
    validations:
      required: true

  - type: input
    id: repo
    attributes:
      label: GitHub Repo
      description: |
        This is extremely important! If this issue can be reproduced on https://github.com/nrwl/nx-examples, you may use that as the repo. 
        If not, please take a few minutes to create a repository that helps us reproduce the issue. This greatly aids in resolving the issue quickly.

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed instructions to reproduce the issue in the repository provided above.
      value: |
        1.
    validations:
      required: true

  - type: textarea
    id: nxcc-report
    attributes:
      label: Nxcc Report
      description: Please paste the output of `nxcc report`. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Failure Logs
      description: Please include any relevant log snippets or files here. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: input
    id: pm
    attributes:
      label: Package Manager Version
      description: |
        If `nxcc report` doesn't work, please provide the name and version of your package manager. 
        You can find this information by running `yarn --version`, `pnpm --version`, or `npm --version`, depending on which package manager you are using.

  - type: checkboxes
    id: os
    attributes:
      label: Operating System
      description: What Operating System are you using?
      options:
        - label: macOS
        - label: Linux
        - label: Windows
        - label: Other (Please specify)

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Is there any other information you can provide?

  - type: markdown
    id: disclaimer
    attributes:
      value: |
        > Please note that if we cannot reproduce the issue, we may prioritise fixing other issues that we can reproduce. Your detailed input is crucial for us to assist you effectively. Thank you!
